fix(change-theme): inform when hyprctl fails (often due to incorrect HIS)
This mostly happens when starting a new Hyprland instance while still
inside a tmux instance; probably there is a better FIXME.

diff --git a/change-theme b/change-theme
--- a/change-theme
+++ b/change-theme
@@ -54,7 +54,10 @@ function change_theme() {
 
   cd "${XDG_CONFIG_HOME}"/hypr
   ln -sf "rose-pine/rose-pine${name}.conf" themes/colors
-  hyprctl reload >/dev/null 2>&1
+  if ! hyprctl reload >/dev/null 2>&1; then
+    printf 'Failed to update for Hyprland.\nInstance Signature out-of-date?\n' >&2
+    exit 1
+  fi
 
   cd "${XDG_CONFIG_HOME}"/nvim
   sed -i "s/variant = \".*\"/variant = \"${pretty_name}\"/" lua/plugins/theme.lua
